version: '3'
services:
  go-sse:
    container_name: go-sse
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - $PWD/.:/app
  rproxy:
    container_name: rproxy
    build:
      context: ./nginx
    ports:
      - 80:80
